
[project]
name = "keras_snn_lib"
version = "0.0.1"
authors = [
    { name="Filipe C. Ferraz", email="filipe.ferraz0@gmail.com" },
]
description = "A Keras-based Python library built to facilitate the implementation of Siamese Neural Networks (SNN)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy == 1.23.5",
    "pandas == 2.1.1",
    "tqdm == 4.66",
    "tensorflow == 2.14",
    "matplotlib == 3.8.0",
    "h5py == 3.10.0"
]